Merging Rust STD side of std-fs integration
twizzler-operating-system/rust pull request #1
Opened 2024-08-05 21:45 UTC by CPTforever

I've added some code that will interface with the Twizzler runtime. This allows user programs to use the Rust std fs interface to access Twizzler objects.

2024-08-06 02:42 UTC, dbittman requested changes
Just some small changes

2024-08-06 02:42 UTC, dbittman commented on library/std/src/sys/hermit/fd.rs
> +        let result = cvt(unsafe { abi::write(self.fd.as_raw_fd(), buf.as_mut_ptr(), buf.len()) })?;
Why is there a change in the hermit code?

2024-08-06 02:42 UTC, dbittman commented on library/std/src/sys/twizzler/fs.rs
> +        println!("opening 1");
We should try to keep the code free of these indicators.

2024-08-06 02:42 UTC, dbittman commented on library/std/src/sys/twizzler/fs.rs
> +        println!("Inited DirBuilder! :)");
Here, too

2024-08-06 02:42 UTC, dbittman commented on library/std/src/sys/twizzler/fs.rs
> +        write!(f, "No")
This should do something better -- write the fd number or something?

2024-08-06 02:42 UTC, dbittman commented on library/std/src/sys/twizzler/mod.rs
> +//#[path = "../unsupported/fs.rs"]
Remove the commented #[attr]

2024-08-07 00:52 UTC, CPTforever commented
Undid change to hermit 
Removed all print statements
Removed commented $[attr]
Added a display trait to FileDesc and a debug trait to FIle so it should print out the file descriptor number

2024-08-07 18:08 UTC, merged